name: Enforce Specific Reviewer Approvals

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  enforce_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Check for Required Approvals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define the mandatory reviewers
          MANDATORY_MANAGER="matx104"
          DEV_SYSOPS_TEAM=("WamiqSid" "Aatika-K")

          # Get the pull request number directly from the environment variable
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Get the list of reviewers who have approved the PR
          APPROVED_REVIEWERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
            | jq -r '.[] | select(.state == "APPROVED") | .user.login')

          # Output for debugging
          echo "Approved Reviewers List: $APPROVED_REVIEWERS"

          # Set up flags to track approval
          MANAGER_APPROVED=0
          DEV_SYSOPS_APPROVED=0

          # Check if each required reviewer has approved
          for reviewer in $APPROVED_REVIEWERS; do
            echo "Checking reviewer: $reviewer"
            if [[ "$reviewer" == "$MANDATORY_MANAGER" ]]; then
              MANAGER_APPROVED=1
              echo "Manager approval received from $reviewer"
            else
              # Loop through DEV_SYSOPS_TEAM to see if any member has approved
              for sysop in "${DEV_SYSOPS_TEAM[@]}"; do
                if [[ "$reviewer" == "$sysop" ]]; then
                  DEV_SYSOPS_APPROVED=1
                  echo "DevSysOps approval received from $reviewer"
                  break
                fi
              done
            fi
          done

          # Output the flag statuses for debugging
          echo "MANAGER_APPROVED: $MANAGER_APPROVED"
          echo "DEV_SYSOPS_APPROVED: $DEV_SYSOPS_APPROVED"

          # Check if both Manager and at least one DevSysOps member have approved
          if [[ $MANAGER_APPROVED -eq 1 && $DEV_SYSOPS_APPROVED -eq 1 ]]; then
            echo "Required approvals received."
          else
            echo "Error: Approval from matx104 is required, along with one approval from either WamiqSid or Aatika-K."
            exit 1
          fi
