name: Enforce Specific Reviewer Approvals

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  enforce_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Approvals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define the mandatory reviewers
          MANDATORY_MANAGER="matx104"
          DEV_SYSOPS_TEAM=("WamiqSid" "Aatika-K")

          # Get the pull request number
          PR_NUMBER=$(jq -r '.number' "$GITHUB_EVENT_PATH")

          # Get the list of reviewers who have approved the PR
          APPROVED_REVIEWERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
            | jq -r '.[] | select(.state == "APPROVED") | .user.login')

          # Set up flags to track approval
          MANAGER_APPROVED=0
          DEV_SYSOPS_APPROVED=0

          # Check if each required reviewer has approved
          for reviewer in $APPROVED_REVIEWERS; do
            if [[ "$reviewer" == "$MANDATORY_MANAGER" ]]; then
              MANAGER_APPROVED=1
            elif [[ " ${DEV_SYSOPS_TEAM[@]} " =~ " $reviewer " ]]; then
              DEV_SYSOPS_APPROVED=1
            fi
          done

          # Output for debugging
          echo "Approved Reviewers: $APPROVED_REVIEWERS"
          echo "MANAGER_APPROVED: $MANAGER_APPROVED"
          echo "DEV_SYSOPS_APPROVED: $DEV_SYSOPS_APPROVED"

          # Check if both Manager and at least one DevSysOps member have approved
          if [[ $MANAGER_APPROVED -eq 1 && $DEV_SYSOPS_APPROVED -eq 1 ]]; then
            echo "Required approvals received."
          else
            echo "Error: Approval from matx104 is required, along with one approval from either WamiqSid or Aatika-K."
            exit 1
          fi
